steps:
- name: 'ubuntu'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    cat app.yaml.example | sed "s/EXAMPLE_PASSWORD/${_PASSWORD}/" > app.yaml
# fetch dependencies
- name: mirror.gcr.io/library/golang
  env: ['GO111MODULE=on']
  args: ['go', 'build', './...']
- name: "gcr.io/cloud-builders/gcloud"
  args: ["app", "deploy"]
timeout: "1600s"
substitutions: 
  _PASSWORD: EXAMPLE_SUBSTITUTION
